Первое задание
js-tasks-ru/jsbasic-20221215_fgolev pull request #1
Opened 2022-12-18 20:54 UTC by MisterFapey

2022-12-18 20:54 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @koalex должен запустить тесты.

2022-12-19 09:34 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-12-19 09:39 UTC, koalex requested changes
Исправить замечание

2022-12-19 09:39 UTC, koalex commented on 0-module/1-task/index.js
> +alert( sum(1)(1) );
Удалить `alert`-ы

2022-12-19 09:39 UTC, koalex commented on 0-module/1-task/index.js
> +function sum(a)  {
Неправильно. Ф-ция должна принимать `m` и `n`, а у вас только один аргумент `a`. 
Вот решение:
```
function sum(m, n) {
    return m + n;
}
```

2022-12-19 15:55 UTC, MisterFapey reviewed
Обновил задание

2022-12-19 17:33 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-12-19 17:35 UTC, koalex approved these changes

2022-12-19 17:35 UTC, merged